name: 'Hello, world'
description: 'Greet someone and record bla bla bla'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The tine we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
